return {
  
  { 'folke/snacks.nvim', priority = 1000, lazy = false,
   opts = {
      animate = { enabled = true, },
      --bigfile = { enabled = false, },
      --bufdelete = { enabled = false, },
      dashboard = { },
      --dim = { enabled = false, },
      --explorer = {  enabled = true },
      --git = { enabled = false, },
      --gitbrowse = { enabled = false, },
      --image = { enabled = false, },
      indent = { enabled = true, },
      --input = { enabled = false, },
      --layout = { enabled = false, },
      --lazygit = { enabled = false, },
      --notifier = { enabled = false, },
      --notify = { enabled = false, },
      --picker = { enabled = true, },
      --profiler = { enabled = false, },
      --quickfile = { enabled = false, },
      --rename = { enabled = false, },
      --scope = { enabled = false, },
      --scratch = { enabled = false, },
      scroll = { enabled = true, },
      statuscolumn = { enabled = false, },
      terminal = { enabled = false, },
      --toggle = { enabled = false, },
      --util = { enabled = false, },
      --win = { enabled = false, },
      --words = { enabled = false, },
      --zen = { enabled = false, },
      }, 
  },

}
